export interface SeedRequirement {
  cpuMin: string;
  cpuRecommended: string | null;
  gpuMin: string;
  gpuRecommended: string | null;
  gpuVramMinGb: number | null;
  gpuVramRecommendedGb: number | null;
  ramMinGb: number;
  ramRecommendedGb: number | null;
  storageMinGb: number;
  storageRecommendedGb: number | null;
  storageType: string | null;
  osRequired: string;
  directxVersion: string | null;
}

export interface SeedGame {
  slug: string;
  title: string;
  developer: string;
  publisher: string;
  releaseDate: string;
  genres: string[];
  description: string;
  coverImageUrl: string;
  minimum: SeedRequirement;
  recommended: SeedRequirement;
}

export const seedGames: SeedGame[] = [
  // ─── TOP AAA TITLES ──────────────────────────────────────────────────────
  {
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Open World", "Sci-Fi", "Action"],
    description:
      "Cyberpunk 2077 is an open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour and body modification.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-3570K",
      cpuRecommended: "AMD FX-8310",
      gpuMin: "NVIDIA GeForce GTX 780",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 70,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-4790",
      cpuRecommended: "AMD Ryzen 3 3200G",
      gpuMin: "NVIDIA GeForce RTX 2060 Super",
      gpuRecommended: "AMD Radeon RX 5700 XT",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 12,
      ramRecommendedGb: 16,
      storageMinGb: 70,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "elden-ring",
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genres: ["Action RPG", "Souls-like", "Open World", "Fantasy"],
    description:
      "Elden Ring is an action RPG developed by FromSoftware and published by Bandai Namco Entertainment. Rise, Tarnished, and be guided by grace.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-8400",
      cpuRecommended: "AMD Ryzen 3 3300X",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 580",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 12,
      ramRecommendedGb: null,
      storageMinGb: 60,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-8700K",
      cpuRecommended: "AMD Ryzen 5 3600X",
      gpuMin: "NVIDIA GeForce GTX 1070",
      gpuRecommended: "AMD Radeon RX Vega 56",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 60,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    genres: ["RPG", "Turn-Based", "Fantasy", "Story Rich"],
    description:
      "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-4690",
      cpuRecommended: "AMD FX-8350",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon RX 480",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 150,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-8700K",
      cpuRecommended: "AMD Ryzen 5 3600",
      gpuMin: "NVIDIA GeForce RTX 2060 Super",
      gpuRecommended: "AMD Radeon RX 5700 XT",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 150,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2019-12-05",
    genres: ["Action", "Adventure", "Open World", "Western"],
    description:
      "Winner of over 175 Game of the Year Awards, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 770",
      gpuRecommended: "AMD Radeon R9 280",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 150,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-4770K",
      cpuRecommended: "AMD Ryzen 5 1500X",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 480",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 12,
      ramRecommendedGb: null,
      storageMinGb: 150,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "gta-v",
    title: "Grand Theft Auto V",
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    releaseDate: "2015-04-14",
    genres: ["Action", "Open World", "Crime", "Multiplayer"],
    description:
      "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4K.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
    minimum: {
      cpuMin: "Intel Core 2 Quad Q6600",
      cpuRecommended: "AMD Phenom 9850",
      gpuMin: "NVIDIA GeForce 9800 GT",
      gpuRecommended: "AMD Radeon HD 4870",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 72,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "10",
    },
    recommended: {
      cpuMin: "Intel Core i5-3470",
      cpuRecommended: "AMD FX-8350",
      gpuMin: "NVIDIA GeForce GTX 660",
      gpuRecommended: "AMD Radeon HD 7870",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 72,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "call-of-duty-modern-warfare-3",
    title: "Call of Duty: Modern Warfare III",
    developer: "Sledgehammer Games",
    publisher: "Activision",
    releaseDate: "2023-11-10",
    genres: ["FPS", "Action", "Multiplayer", "Military"],
    description:
      "The ultimate threat awaits in Call of Duty: Modern Warfare III. Fight alongside Task Force 141 in a globe-trotting single-player campaign.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2519060/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-6600",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 149,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-6700K",
      cpuRecommended: "AMD Ryzen 5 1600X",
      gpuMin: "NVIDIA GeForce GTX 1080",
      gpuRecommended: "AMD Radeon RX 6600 XT",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 149,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 11",
      directxVersion: "12",
    },
  },
  {
    slug: "starfield",
    title: "Starfield",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    releaseDate: "2023-09-06",
    genres: ["RPG", "Open World", "Sci-Fi", "Space"],
    description:
      "Starfield is the first new universe in 25 years from Bethesda Game Studios. Create any character you want and explore with unparalleled freedom.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg",
    minimum: {
      cpuMin: "AMD Ryzen 5 2600X",
      cpuRecommended: "Intel Core i7-6800K",
      gpuMin: "AMD Radeon RX 5700",
      gpuRecommended: "NVIDIA GeForce GTX 1070 Ti",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 125,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "AMD Ryzen 5 3600X",
      cpuRecommended: "Intel Core i5-10600K",
      gpuMin: "AMD Radeon RX 6800 XT",
      gpuRecommended: "NVIDIA GeForce RTX 2080",
      gpuVramMinGb: 16,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 125,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 11",
      directxVersion: "12",
    },
  },
  {
    slug: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    releaseDate: "2023-02-10",
    genres: ["Action RPG", "Open World", "Fantasy", "Adventure"],
    description:
      "Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-6600",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-8700",
      cpuRecommended: "AMD Ryzen 5 3600",
      gpuMin: "NVIDIA GeForce RTX 2070",
      gpuRecommended: "AMD Radeon RX 5700 XT",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2015-05-19",
    genres: ["RPG", "Open World", "Fantasy", "Story Rich"],
    description:
      "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD Phenom II X4 940",
      gpuMin: "NVIDIA GeForce GTX 660",
      gpuRecommended: "AMD Radeon HD 7870",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 6,
      ramRecommendedGb: null,
      storageMinGb: 50,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-3770",
      cpuRecommended: "AMD FX-8350",
      gpuMin: "NVIDIA GeForce GTX 770",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 50,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "god-of-war",
    title: "God of War",
    developer: "Santa Monica Studio",
    publisher: "PlayStation PC LLC",
    releaseDate: "2022-01-14",
    genres: ["Action", "Adventure", "Story Rich", "Mythology"],
    description:
      "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon R9 290X",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 70,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-6600K",
      cpuRecommended: "AMD Ryzen 5 2400G",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 570",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 70,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "spider-man-remastered",
    title: "Marvel's Spider-Man Remastered",
    developer: "Insomniac Games",
    publisher: "PlayStation PC LLC",
    releaseDate: "2022-08-12",
    genres: ["Action", "Adventure", "Open World", "Superhero"],
    description:
      "In Marvel's Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide in an original action-packed story.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-4160",
      cpuRecommended: "AMD equivalent",
      gpuMin: "NVIDIA GeForce GTX 950",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 75,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-4670",
      cpuRecommended: "AMD Ryzen 5 1600",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 580",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 75,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "diablo-iv",
    title: "Diablo IV",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    releaseDate: "2023-06-06",
    genres: ["Action RPG", "Dungeon Crawler", "Dark Fantasy", "Multiplayer"],
    description:
      "Diablo IV is the next-gen action RPG experience with endless evil to slaughter, countless abilities to master, nightmarish Dungeons, and legendary loot.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2344520/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD FX-8350",
      gpuMin: "NVIDIA GeForce GTX 660",
      gpuRecommended: "AMD Radeon R9 280",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 90,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-4670K",
      cpuRecommended: "AMD Ryzen 3 1300X",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 90,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  // ─── COMPETITIVE / ESPORTS ─────────────────────────────────────────────────
  {
    slug: "valorant",
    title: "VALORANT",
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseDate: "2020-06-02",
    genres: ["FPS", "Tactical", "Competitive", "Multiplayer"],
    description:
      "VALORANT is a 5v5 character-based tactical shooter where precise gunplay meets unique agent abilities.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2161700/header.jpg",
    minimum: {
      cpuMin: "Intel Core 2 Duo E8400",
      cpuRecommended: "AMD Athlon 200GE",
      gpuMin: "Intel HD 3000",
      gpuRecommended: "AMD Radeon R5 200",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i3-4150",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GT 730",
      gpuRecommended: "AMD Radeon R7 240",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "league-of-legends",
    title: "League of Legends",
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseDate: "2009-10-27",
    genres: ["MOBA", "Strategy", "Competitive", "Multiplayer"],
    description:
      "League of Legends is a team-based strategy game where two teams of five powerful champions face off to destroy the other's base.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/20590/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-530",
      cpuRecommended: "AMD A6-3650",
      gpuMin: "NVIDIA GeForce 9600 GT",
      gpuRecommended: "Intel HD 4600",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 16,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-3300",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 560",
      gpuRecommended: "AMD Radeon HD 6950",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 16,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "counter-strike-2",
    title: "Counter-Strike 2",
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2023-09-27",
    genres: ["FPS", "Tactical", "Competitive", "Multiplayer"],
    description:
      "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-750",
      cpuRecommended: "AMD Phenom II X4 965",
      gpuMin: "NVIDIA GeForce GT 630",
      gpuRecommended: "AMD Radeon HD 6670",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-2400",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 660",
      gpuRecommended: "AMD Radeon HD 7850",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "fortnite",
    title: "Fortnite",
    developer: "Epic Games",
    publisher: "Epic Games",
    releaseDate: "2017-07-25",
    genres: ["Battle Royale", "Shooter", "Multiplayer", "Building"],
    description:
      "Create, play, and battle with friends for free in Fortnite. Be the last player standing in Battle Royale and Zero Build.",
    coverImageUrl: "https://cdn2.unrealengine.com/fortnite-nvidia-geforcenow-1920x1080-56ea6fa2d64a.jpg",
    minimum: {
      cpuMin: "Intel Core i3-3225",
      cpuRecommended: "AMD equivalent",
      gpuMin: "Intel HD 4000",
      gpuRecommended: "AMD Radeon Vega 8",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-7300U",
      cpuRecommended: "AMD Ryzen 3 3300U",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon R9 280",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "apex-legends",
    title: "Apex Legends",
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    releaseDate: "2020-11-05",
    genres: ["Battle Royale", "FPS", "Hero Shooter", "Multiplayer"],
    description:
      "Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-6300",
      cpuRecommended: "AMD FX-4350",
      gpuMin: "NVIDIA GeForce GT 640",
      gpuRecommended: "AMD Radeon HD 7730",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 6,
      ramRecommendedGb: null,
      storageMinGb: 75,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-3570K",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 75,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "rainbow-six-siege",
    title: "Tom Clancy's Rainbow Six Siege",
    developer: "Ubisoft Montreal",
    publisher: "Ubisoft",
    releaseDate: "2015-12-01",
    genres: ["FPS", "Tactical", "Multiplayer", "Competitive"],
    description:
      "Rainbow Six Siege is a realistic, tactical team-based shooter where superior planning and execution triumph.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/359550/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-560",
      cpuRecommended: "AMD Phenom II X4 945",
      gpuMin: "NVIDIA GeForce GTX 460",
      gpuRecommended: "AMD Radeon HD 5870",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 6,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD FX-8120",
      gpuMin: "NVIDIA GeForce GTX 670",
      gpuRecommended: "AMD Radeon HD 7970",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 85,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  // ─── MORE AAA TITLES ──────────────────────────────────────────────────────
  {
    slug: "assassins-creed-valhalla",
    title: "Assassin's Creed Valhalla",
    developer: "Ubisoft Montreal",
    publisher: "Ubisoft",
    releaseDate: "2022-12-06",
    genres: ["Action RPG", "Open World", "Stealth", "Historical"],
    description:
      "Become a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2208920/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-4460",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon R9 380",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 160,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-4790",
      cpuRecommended: "AMD Ryzen 5 1600",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 570",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 160,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "horizon-zero-dawn",
    title: "Horizon Zero Dawn Complete Edition",
    developer: "Guerrilla Games",
    publisher: "PlayStation PC LLC",
    releaseDate: "2020-08-07",
    genres: ["Action RPG", "Open World", "Sci-Fi", "Adventure"],
    description:
      "Experience Aloy's legendary quest to unravel the mysteries of a future Earth ruled by Machines.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 780",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 100,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-4770K",
      cpuRecommended: "AMD Ryzen 5 1500X",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 580",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 100,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "doom-eternal",
    title: "DOOM Eternal",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    releaseDate: "2020-03-20",
    genres: ["FPS", "Action", "Sci-Fi", "Gore"],
    description:
      "Hell's armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 1050 Ti",
      gpuRecommended: "AMD Radeon R9 280",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 80,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-6700K",
      cpuRecommended: "AMD Ryzen 7 1800X",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 480",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 80,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "forza-horizon-5",
    title: "Forza Horizon 5",
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    releaseDate: "2021-11-09",
    genres: ["Racing", "Open World", "Multiplayer", "Simulation"],
    description:
      "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-4460",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 110,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-8400",
      cpuRecommended: "AMD Ryzen 5 1500X",
      gpuMin: "NVIDIA GeForce GTX 1070",
      gpuRecommended: "AMD Radeon RX 590",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 110,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "monster-hunter-world",
    title: "Monster Hunter: World",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2018-08-09",
    genres: ["Action RPG", "Hunting", "Co-op", "Fantasy"],
    description:
      "Welcome to a new world! In Monster Hunter: World, the latest installment in the series, you can enjoy the ultimate hunting experience.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-4460",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 760",
      gpuRecommended: "AMD Radeon R7 260x",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 52,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-3770",
      cpuRecommended: "AMD Ryzen 5 1500X",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 570X",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 52,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "rust",
    title: "Rust",
    developer: "Facepunch Studios",
    publisher: "Facepunch Studios",
    releaseDate: "2018-02-08",
    genres: ["Survival", "Open World", "Multiplayer", "Crafting"],
    description:
      "The only aim in Rust is to survive. Everything wants you to die - the island's wildlife, other inhabitants, the environment.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg",
    minimum: {
      cpuMin: "Intel Core i7-3770",
      cpuRecommended: "AMD FX-9590",
      gpuMin: "NVIDIA GeForce GTX 670",
      gpuRecommended: "AMD Radeon R9 280",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 10,
      ramRecommendedGb: null,
      storageMinGb: 35,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-4790K",
      cpuRecommended: "AMD Ryzen 5 1600",
      gpuMin: "NVIDIA GeForce GTX 980",
      gpuRecommended: "AMD Radeon R9 Fury",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 35,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "destiny-2",
    title: "Destiny 2",
    developer: "Bungie",
    publisher: "Bungie",
    releaseDate: "2019-10-01",
    genres: ["FPS", "Looter Shooter", "MMO", "Sci-Fi"],
    description:
      "Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-3250",
      cpuRecommended: "AMD FX-4350",
      gpuMin: "NVIDIA GeForce GTX 660",
      gpuRecommended: "AMD Radeon HD 7850",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 6,
      ramRecommendedGb: null,
      storageMinGb: 105,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-7400",
      cpuRecommended: "AMD Ryzen 3 3100",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon R9 390",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 105,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "warzone",
    title: "Call of Duty: Warzone",
    developer: "Infinity Ward",
    publisher: "Activision",
    releaseDate: "2022-11-16",
    genres: ["Battle Royale", "FPS", "Multiplayer", "Military"],
    description:
      "Welcome to Warzone, the massive free-to-play combat arena which features the Battle Royale and DMZ modes.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-6100",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon RX 470",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 125,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-6600K",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 580",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 12,
      ramRecommendedGb: null,
      storageMinGb: 125,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "fallout-4",
    title: "Fallout 4",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    releaseDate: "2015-11-10",
    genres: ["RPG", "Open World", "Post-apocalyptic", "FPS"],
    description:
      "Bethesda Game Studios welcomes you to the world of Fallout 4 - their most ambitious game ever, and the next generation of open-world gaming.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/377160/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-2300",
      cpuRecommended: "AMD Phenom II X4 945",
      gpuMin: "NVIDIA GeForce GTX 550 Ti",
      gpuRecommended: "AMD Radeon HD 7870",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-4790",
      cpuRecommended: "AMD FX-9590",
      gpuMin: "NVIDIA GeForce GTX 780",
      gpuRecommended: "AMD Radeon R9 290X",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 30,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "skyrim-special-edition",
    title: "The Elder Scrolls V: Skyrim Special Edition",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    releaseDate: "2016-10-28",
    genres: ["RPG", "Open World", "Fantasy", "Adventure"],
    description:
      "Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-750",
      cpuRecommended: "AMD Phenom II X4 945",
      gpuMin: "NVIDIA GeForce GTX 470",
      gpuRecommended: "AMD Radeon HD 7870",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 12,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-2400",
      cpuRecommended: "AMD FX-8320",
      gpuMin: "NVIDIA GeForce GTX 780",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 12,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "dark-souls-iii",
    title: "Dark Souls III",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2016-04-12",
    genres: ["Action RPG", "Souls-like", "Dark Fantasy", "Difficult"],
    description:
      "Dark Souls III continues to push the boundaries with the latest chapter in the critically-acclaimed and genre-defining series.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-2100",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 750 Ti",
      gpuRecommended: "AMD Radeon HD 7950",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 25,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-3770",
      cpuRecommended: "AMD FX-8350",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 25,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "sekiro-shadows-die-twice",
    title: "Sekiro: Shadows Die Twice",
    developer: "FromSoftware",
    publisher: "Activision",
    releaseDate: "2019-03-22",
    genres: ["Action", "Souls-like", "Ninja", "Difficult"],
    description:
      "Game of the Year - The Game Awards 2019. Carve your own clever path to vengeance in this critically acclaimed adventure.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-2100",
      cpuRecommended: "AMD FX-6300",
      gpuMin: "NVIDIA GeForce GTX 760",
      gpuRecommended: "AMD Radeon HD 7950",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 25,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-2500K",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 970",
      gpuRecommended: "AMD Radeon RX 570",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 25,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "minecraft",
    title: "Minecraft",
    developer: "Mojang Studios",
    publisher: "Xbox Game Studios",
    releaseDate: "2011-11-18",
    genres: ["Sandbox", "Survival", "Adventure", "Multiplayer"],
    description:
      "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode or survival mode.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/204100/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-3210",
      cpuRecommended: "AMD A8-7600",
      gpuMin: "Intel HD Graphics 4000",
      gpuRecommended: "AMD Radeon R5 series",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 4,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-4690",
      cpuRecommended: "AMD Ryzen 5 1600",
      gpuMin: "NVIDIA GeForce GTX 780",
      gpuRecommended: "AMD Radeon R9 290",
      gpuVramMinGb: 3,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 4,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "dying-light-2",
    title: "Dying Light 2 Stay Human",
    developer: "Techland",
    publisher: "Techland",
    releaseDate: "2022-02-04",
    genres: ["Action RPG", "Zombies", "Open World", "Parkour"],
    description:
      "Over twenty years ago in Harran, we fought the virus - and lost. Now, we're losing again. The City, one of the last large human settlements, is torn by conflict.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/534380/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-9100",
      cpuRecommended: "AMD Ryzen 3 2300X",
      gpuMin: "NVIDIA GeForce GTX 1050 Ti",
      gpuRecommended: "AMD Radeon RX 560",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 60,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i5-8600K",
      cpuRecommended: "AMD Ryzen 5 3600X",
      gpuMin: "NVIDIA GeForce RTX 2060",
      gpuRecommended: "AMD Radeon RX Vega 56",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 60,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "death-stranding",
    title: "Death Stranding Director's Cut",
    developer: "Kojima Productions",
    publisher: "505 Games",
    releaseDate: "2022-03-30",
    genres: ["Action", "Adventure", "Sci-Fi", "Story Rich"],
    description:
      "From legendary game creator Hideo Kojima comes a genre-defying experience, now expanded in this definitive Director's Cut.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1850570/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-3470",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 1050 Ti",
      gpuRecommended: "AMD Radeon RX 570",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 80,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
    recommended: {
      cpuMin: "Intel Core i7-3770",
      cpuRecommended: "AMD Ryzen 5 1600",
      gpuMin: "NVIDIA GeForce GTX 1060",
      gpuRecommended: "AMD Radeon RX 590",
      gpuVramMinGb: 6,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 80,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "12",
    },
  },
  {
    slug: "total-war-warhammer-iii",
    title: "Total War: WARHAMMER III",
    developer: "Creative Assembly",
    publisher: "SEGA",
    releaseDate: "2022-02-17",
    genres: ["Strategy", "Turn-Based", "Fantasy", "RTS"],
    description:
      "The cataclysmic conclusion to the Total War: WARHAMMER trilogy is here. Rally your forces and enter the Realm of Chaos.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1142710/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-2120",
      cpuRecommended: "AMD Ryzen 3 series",
      gpuMin: "NVIDIA GeForce GTX 900 series",
      gpuRecommended: "AMD Radeon RX 400 series",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 6,
      ramRecommendedGb: null,
      storageMinGb: 120,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-6600",
      cpuRecommended: "AMD Ryzen 5 2600X",
      gpuMin: "NVIDIA GeForce GTX 1070",
      gpuRecommended: "AMD Radeon RX 5700",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 120,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  // ─── INDIE & POPULAR ───────────────────────────────────────────────────────
  {
    slug: "hades-ii",
    title: "Hades II",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseDate: "2024-05-06",
    genres: ["Action Roguelike", "Dungeon Crawler", "Mythology", "Story Rich"],
    description:
      "Battle beyond the Underworld of Greek myth in the sequel to the smash-hit God-like roguelike.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg",
    minimum: {
      cpuMin: "Intel Core i3-2100",
      cpuRecommended: "AMD FX-4300",
      gpuMin: "NVIDIA GeForce GTX 750",
      gpuRecommended: "AMD Radeon R7 260X",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 10,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i5-4570",
      cpuRecommended: "AMD Ryzen 5 1400",
      gpuMin: "NVIDIA GeForce GTX 960",
      gpuRecommended: "AMD Radeon R9 380",
      gpuVramMinGb: 4,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 10,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "palworld",
    title: "Palworld",
    developer: "Pocketpair",
    publisher: "Pocketpair",
    releaseDate: "2024-01-19",
    genres: ["Survival", "Open World", "Crafting", "Multiplayer"],
    description:
      "Fight, farm, build and work alongside mysterious creatures called Pals in this completely new multiplayer, open world survival and crafting game!",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/header.jpg",
    minimum: {
      cpuMin: "Intel Core i5-3570K",
      cpuRecommended: "AMD Ryzen 3 1200",
      gpuMin: "NVIDIA GeForce GTX 1050",
      gpuRecommended: "AMD Radeon RX 560",
      gpuVramMinGb: 2,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 40,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
    recommended: {
      cpuMin: "Intel Core i7-8700",
      cpuRecommended: "AMD Ryzen 5 3600",
      gpuMin: "NVIDIA GeForce RTX 2070",
      gpuRecommended: "AMD Radeon RX 5700",
      gpuVramMinGb: 8,
      gpuVramRecommendedGb: null,
      ramMinGb: 16,
      ramRecommendedGb: null,
      storageMinGb: 40,
      storageRecommendedGb: null,
      storageType: "SSD",
      osRequired: "Windows 10",
      directxVersion: "11",
    },
  },
  {
    slug: "stardew-valley",
    title: "Stardew Valley",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    genres: ["Farming Sim", "RPG", "Pixel Graphics", "Relaxing"],
    description:
      "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg",
    minimum: {
      cpuMin: "Intel Core 2 Duo",
      cpuRecommended: "AMD equivalent",
      gpuMin: "256 MB video memory, shader model 3.0+",
      gpuRecommended: null,
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 2,
      ramRecommendedGb: null,
      storageMinGb: 1,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "10",
    },
    recommended: {
      cpuMin: "Intel Core i5",
      cpuRecommended: "AMD equivalent",
      gpuMin: "NVIDIA GeForce GTX 260",
      gpuRecommended: "AMD Radeon HD 5770",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 2,
      ramRecommendedGb: null,
      storageMinGb: 1,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "10",
    },
  },
  {
    slug: "terraria",
    title: "Terraria",
    developer: "Re-Logic",
    publisher: "Re-Logic",
    releaseDate: "2011-05-16",
    genres: ["Sandbox", "Survival", "Adventure", "2D"],
    description:
      "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. The world is your canvas!",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg",
    minimum: {
      cpuMin: "Intel Core 2 Duo 2.0 GHz",
      cpuRecommended: "AMD equivalent",
      gpuMin: "128 MB video memory",
      gpuRecommended: null,
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 2,
      ramRecommendedGb: null,
      storageMinGb: 1,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "9",
    },
    recommended: {
      cpuMin: "Intel Core 2 Duo 3.0 GHz",
      cpuRecommended: "AMD equivalent",
      gpuMin: "256 MB video memory",
      gpuRecommended: null,
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 1,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "9",
    },
  },
  {
    slug: "hollow-knight",
    title: "Hollow Knight",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    genres: ["Metroidvania", "Action", "Platformer", "Hand-Drawn"],
    description:
      "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
    minimum: {
      cpuMin: "Intel Core 2 Duo E5200",
      cpuRecommended: "AMD equivalent",
      gpuMin: "NVIDIA GeForce 9800 GTX+",
      gpuRecommended: "AMD Radeon HD 5750",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 4,
      ramRecommendedGb: null,
      storageMinGb: 9,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "10",
    },
    recommended: {
      cpuMin: "Intel Core i5",
      cpuRecommended: "AMD equivalent",
      gpuMin: "NVIDIA GeForce GTX 560",
      gpuRecommended: "AMD Radeon HD 6870",
      gpuVramMinGb: 1,
      gpuVramRecommendedGb: null,
      ramMinGb: 8,
      ramRecommendedGb: null,
      storageMinGb: 9,
      storageRecommendedGb: null,
      storageType: null,
      osRequired: "Windows 10",
      directxVersion: "10",
    },
  },
  // Continue with more games to reach 100...
  {
    slug: "resident-evil-4-remake",
    title: "Resident Evil 4 Remake",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2023-03-24",
    genres: ["Horror", "Action", "Survival", "Third-Person Shooter"],
    description: "Resident Evil 4 joins Leon S. Kennedy six years after the biological disaster in Raccoon City.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
    minimum: { cpuMin: "AMD Ryzen 3 1200", cpuRecommended: "Intel Core i5-7500", gpuMin: "AMD Radeon RX 560", gpuRecommended: "NVIDIA GeForce GTX 1050 Ti", gpuVramMinGb: 4, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 55, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "AMD Ryzen 5 3600", cpuRecommended: "Intel Core i7-8700", gpuMin: "AMD Radeon RX 5700", gpuRecommended: "NVIDIA GeForce RTX 2070", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 55, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "dota-2",
    title: "Dota 2",
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2013-07-09",
    genres: ["MOBA", "Strategy", "Competitive", "Multiplayer"],
    description: "Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
    minimum: { cpuMin: "Intel Core 2 Duo E4400", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce 8600 GT", gpuRecommended: "AMD Radeon HD 2600", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 60, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i3-2120", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce GTX 650", gpuRecommended: "AMD Radeon HD 7750", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 60, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "pubg-battlegrounds",
    title: "PUBG: BATTLEGROUNDS",
    developer: "KRAFTON",
    publisher: "KRAFTON",
    releaseDate: "2017-12-21",
    genres: ["Battle Royale", "FPS", "Survival", "Multiplayer"],
    description: "Land on strategic locations, loot weapons and supplies, and survive to become the last team standing.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg",
    minimum: { cpuMin: "Intel Core i5-4430", cpuRecommended: "AMD FX-6300", gpuMin: "NVIDIA GeForce GTX 960", gpuRecommended: "AMD Radeon R7 370", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 40, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1060", gpuRecommended: "AMD Radeon RX 580", gpuVramMinGb: 3, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "overwatch-2",
    title: "Overwatch 2",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    releaseDate: "2023-08-10",
    genres: ["FPS", "Hero Shooter", "Competitive", "Multiplayer"],
    description: "Overwatch 2 is a free-to-play, team-based action game set in an optimistic future.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2357570/header.jpg",
    minimum: { cpuMin: "Intel Core i3-540", cpuRecommended: "AMD Phenom II X3 720", gpuMin: "NVIDIA GeForce GTX 460", gpuRecommended: "AMD Radeon HD 4850", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 6, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-6600", cpuRecommended: "AMD Ryzen 5 1400", gpuMin: "NVIDIA GeForce GTX 1060", gpuRecommended: "AMD Radeon R9 380", gpuVramMinGb: 3, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "dead-by-daylight",
    title: "Dead by Daylight",
    developer: "Behaviour Interactive",
    publisher: "Behaviour Interactive",
    releaseDate: "2016-06-14",
    genres: ["Horror", "Survival", "Multiplayer", "Asymmetric"],
    description: "Dead by Daylight is a multiplayer action horror game where one player takes on the role of a savage Killer.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/381210/header.jpg",
    minimum: { cpuMin: "Intel Core i3-4170", cpuRecommended: "AMD FX-8120", gpuMin: "NVIDIA GeForce GTX 460", gpuRecommended: "AMD Radeon HD 6850", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-6600", cpuRecommended: "AMD Ryzen 5 1400", gpuMin: "NVIDIA GeForce GTX 760", gpuRecommended: "AMD Radeon R9 280", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "warframe",
    title: "Warframe",
    developer: "Digital Extremes",
    publisher: "Digital Extremes",
    releaseDate: "2013-03-25",
    genres: ["Action", "Looter Shooter", "Sci-Fi", "Free to Play"],
    description: "Awaken as an unstoppable warrior and battle alongside your friends in this story-driven free-to-play online action game.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg",
    minimum: { cpuMin: "Intel Core 2 Duo E6400", cpuRecommended: "AMD Athlon 64 X2", gpuMin: "NVIDIA GeForce 8600 GT", gpuRecommended: "AMD Radeon HD 3600", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-2500K", cpuRecommended: "AMD FX-6300", gpuMin: "NVIDIA GeForce GTX 660", gpuRecommended: "AMD Radeon HD 7850", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 50, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "path-of-exile-2",
    title: "Path of Exile 2",
    developer: "Grinding Gear Games",
    publisher: "Grinding Gear Games",
    releaseDate: "2024-12-06",
    genres: ["Action RPG", "Dungeon Crawler", "Dark Fantasy", "Free to Play"],
    description: "Path of Exile 2 is a next generation Action RPG created by Grinding Gear Games.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2694490/header.jpg",
    minimum: { cpuMin: "Intel Core i7-7700", cpuRecommended: "AMD Ryzen 5 2500X", gpuMin: "NVIDIA GeForce GTX 960", gpuRecommended: "AMD Radeon RX 570", gpuVramMinGb: 3, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i5-10500", cpuRecommended: "AMD Ryzen 5 3600", gpuMin: "NVIDIA GeForce RTX 2060", gpuRecommended: "AMD Radeon RX 5600 XT", gpuVramMinGb: 6, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "battlefield-2042",
    title: "Battlefield 2042",
    developer: "DICE",
    publisher: "Electronic Arts",
    releaseDate: "2021-11-19",
    genres: ["FPS", "Multiplayer", "Military", "War"],
    description: "Battlefield 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1517290/header.jpg",
    minimum: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1050 Ti", gpuRecommended: "AMD Radeon RX 570", gpuVramMinGb: 4, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i7-4790", cpuRecommended: "AMD Ryzen 7 2700X", gpuMin: "NVIDIA GeForce RTX 3060", gpuRecommended: "AMD Radeon RX 6600 XT", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "marvel-rivals",
    title: "Marvel Rivals",
    developer: "NetEase Games",
    publisher: "NetEase Games",
    releaseDate: "2024-12-06",
    genres: ["Hero Shooter", "Third-Person Shooter", "Multiplayer", "Superhero"],
    description: "Marvel Rivals is a Super Hero Team-Based PVP Shooter! Assemble an ever-evolving all-star squad of Super Heroes and Super Villains.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2767030/header.jpg",
    minimum: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1060", gpuRecommended: "AMD Radeon RX 580", gpuVramMinGb: 6, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 70, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i7-10700K", cpuRecommended: "AMD Ryzen 5 5600X", gpuMin: "NVIDIA GeForce RTX 2060 Super", gpuRecommended: "AMD Radeon RX 5700 XT", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 70, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "ffvii-remake",
    title: "Final Fantasy VII Remake Intergrade",
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: "2022-06-17",
    genres: ["RPG", "Action", "Story Rich", "Fantasy"],
    description: "The world is under the control of Shinra, a corporation that controls the planet's life force as mako energy.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1462040/header.jpg",
    minimum: { cpuMin: "Intel Core i5-3330", cpuRecommended: "AMD FX-8350", gpuMin: "NVIDIA GeForce GTX 780", gpuRecommended: "AMD Radeon RX 480", gpuVramMinGb: 3, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i7-3770", cpuRecommended: "AMD Ryzen 3 3100", gpuMin: "NVIDIA GeForce GTX 1080", gpuRecommended: "AMD Radeon RX 5700", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 12, ramRecommendedGb: null, storageMinGb: 100, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "ghost-of-tsushima",
    title: "Ghost of Tsushima Director's Cut",
    developer: "Sucker Punch Productions",
    publisher: "PlayStation PC LLC",
    releaseDate: "2024-05-16",
    genres: ["Action", "Adventure", "Open World", "Samurai"],
    description: "Forge a new path and wage an unconventional war for the freedom of Tsushima.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
    minimum: { cpuMin: "Intel Core i3-7100", cpuRecommended: "AMD Ryzen 3 1200", gpuMin: "NVIDIA GeForce GTX 960", gpuRecommended: "AMD Radeon RX 5500 XT", gpuVramMinGb: 4, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 75, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i5-8600", cpuRecommended: "AMD Ryzen 5 3600", gpuMin: "NVIDIA GeForce RTX 2060", gpuRecommended: "AMD Radeon RX 5600 XT", gpuVramMinGb: 6, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 75, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "hitman-3",
    title: "HITMAN World of Assassination",
    developer: "IO Interactive",
    publisher: "IO Interactive",
    releaseDate: "2022-01-20",
    genres: ["Stealth", "Action", "Sandbox", "Assassination"],
    description: "Enter the world of the ultimate assassin. HITMAN World of Assassination brings together the best of HITMAN.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1659040/header.jpg",
    minimum: { cpuMin: "Intel Core i5-2500K", cpuRecommended: "AMD Phenom II X4 940", gpuMin: "NVIDIA GeForce GTX 660", gpuRecommended: "AMD Radeon HD 7870", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 80, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i7-4790", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1070", gpuRecommended: "AMD Radeon RX Vega 56", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 80, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "subnautica",
    title: "Subnautica",
    developer: "Unknown Worlds Entertainment",
    publisher: "Unknown Worlds Entertainment",
    releaseDate: "2018-01-23",
    genres: ["Survival", "Adventure", "Open World", "Underwater"],
    description: "Descend into the depths of an alien underwater world filled with wonder and peril.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/264710/header.jpg",
    minimum: { cpuMin: "Intel Core i3-2100", cpuRecommended: "AMD equivalent", gpuMin: "Intel HD 4600", gpuRecommended: "NVIDIA GeForce GTX 550 Ti", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 20, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-2500K", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce GTX 770", gpuRecommended: "AMD Radeon R9 280", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 20, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "no-mans-sky",
    title: "No Man's Sky",
    developer: "Hello Games",
    publisher: "Hello Games",
    releaseDate: "2016-08-12",
    genres: ["Adventure", "Survival", "Open World", "Space"],
    description: "No Man's Sky is a game about exploration and survival in an infinite procedurally generated universe.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg",
    minimum: { cpuMin: "Intel Core i3-2100", cpuRecommended: "AMD FX-4300", gpuMin: "NVIDIA GeForce GTX 480", gpuRecommended: "AMD Radeon HD 7870", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 15, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1060", gpuRecommended: "AMD Radeon RX 580", gpuVramMinGb: 3, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 15, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "the-finals",
    title: "THE FINALS",
    developer: "Embark Studios",
    publisher: "Embark Studios",
    releaseDate: "2023-12-08",
    genres: ["FPS", "Multiplayer", "Destruction", "Competitive"],
    description: "THE FINALS is the ultimate combat-centered game show where you and your team fight for fame, riches, and glory.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2073850/header.jpg",
    minimum: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1050 Ti", gpuRecommended: "AMD Radeon RX 580", gpuVramMinGb: 4, gpuVramRecommendedGb: null, ramMinGb: 12, ramRecommendedGb: null, storageMinGb: 30, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "12" },
    recommended: { cpuMin: "Intel Core i7-9700K", cpuRecommended: "AMD Ryzen 5 3600", gpuMin: "NVIDIA GeForce RTX 2070", gpuRecommended: "AMD Radeon RX 5700 XT", gpuVramMinGb: 8, gpuVramRecommendedGb: null, ramMinGb: 16, ramRecommendedGb: null, storageMinGb: 30, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "12" },
  },
  {
    slug: "dayz",
    title: "DayZ",
    developer: "Bohemia Interactive",
    publisher: "Bohemia Interactive",
    releaseDate: "2018-12-13",
    genres: ["Survival", "Zombies", "Open World", "Multiplayer"],
    description: "How long can you survive a post-apocalyptic world? A land overrun by the infected, where you are one of the few immune.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/221100/header.jpg",
    minimum: { cpuMin: "Intel Core i5-4430", cpuRecommended: "AMD FX-6300", gpuMin: "NVIDIA GeForce GTX 760", gpuRecommended: "AMD Radeon R9 270X", gpuVramMinGb: 2, gpuVramRecommendedGb: null, ramMinGb: 8, ramRecommendedGb: null, storageMinGb: 25, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "11" },
    recommended: { cpuMin: "Intel Core i5-6600K", cpuRecommended: "AMD Ryzen 5 1600", gpuMin: "NVIDIA GeForce GTX 1060", gpuRecommended: "AMD Radeon RX 580", gpuVramMinGb: 6, gpuVramRecommendedGb: null, ramMinGb: 12, ramRecommendedGb: null, storageMinGb: 30, storageRecommendedGb: null, storageType: "SSD", osRequired: "Windows 10", directxVersion: "11" },
  },
  {
    slug: "rocket-league",
    title: "Rocket League",
    developer: "Psyonix",
    publisher: "Psyonix",
    releaseDate: "2015-07-07",
    genres: ["Sports", "Racing", "Multiplayer", "Competitive"],
    description: "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg",
    minimum: { cpuMin: "Intel Core 2 Duo E4400", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce 7600 GT", gpuRecommended: "AMD Radeon HD 2600", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 20, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
    recommended: { cpuMin: "Intel Core 2 Quad Q6600", cpuRecommended: "AMD Phenom II X4", gpuMin: "NVIDIA GeForce GTX 260", gpuRecommended: "AMD Radeon HD 4850", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 20, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
  },
  {
    slug: "left-4-dead-2",
    title: "Left 4 Dead 2",
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2009-11-17",
    genres: ["FPS", "Zombies", "Co-op", "Multiplayer"],
    description: "Set in the zombie apocalypse, Left 4 Dead 2 is the sequel to the award-winning Left 4 Dead.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/550/header.jpg",
    minimum: { cpuMin: "Intel Core 2 Duo E4400", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce 7600 GT", gpuRecommended: "AMD Radeon HD 2600", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 2, ramRecommendedGb: null, storageMinGb: 13, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
    recommended: { cpuMin: "Intel Core 2 Duo E6600", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce GTX 260", gpuRecommended: "AMD Radeon HD 5770", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 4, ramRecommendedGb: null, storageMinGb: 13, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
  },
  {
    slug: "team-fortress-2",
    title: "Team Fortress 2",
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2007-10-10",
    genres: ["FPS", "Class-Based", "Multiplayer", "Free to Play"],
    description: "Nine distinct classes provide a broad range of tactical abilities and personalities.",
    coverImageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg",
    minimum: { cpuMin: "Intel Core 2 Duo 1.7 GHz", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce GT 120", gpuRecommended: "AMD Radeon HD 2400", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 1, ramRecommendedGb: null, storageMinGb: 15, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
    recommended: { cpuMin: "Intel Core 2 Duo 2.4 GHz", cpuRecommended: "AMD equivalent", gpuMin: "NVIDIA GeForce 8600 GT", gpuRecommended: "AMD Radeon HD 2600", gpuVramMinGb: 1, gpuVramRecommendedGb: null, ramMinGb: 2, ramRecommendedGb: null, storageMinGb: 15, storageRecommendedGb: null, storageType: null, osRequired: "Windows 10", directxVersion: "9" },
  },
] as const;
